name: Deploy Lagitakost to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            cd ${{ secrets.SERVER_PATH }}
            git pull origin main
            echo "✅ Deploy selesai"
          EOF
